config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :location_types

  resources :addresses

  resources :phones

  resources :people

end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :addresses
  has_many :phones

  accepts_nested_attributes_for :addresses, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :phones, allow_destroy: true, reject_if: :all_blank
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new

    2.times { @person.phones.build }
    2.times { @person.addresses.build }
  end

  # GET /people/1/edit
  def edit
    (2 - @person.phones.size).times { @person.phones.build }
    (2 - @person.addresses.size).times { @person.addresses.build }
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit([:name,
        phones_attributes: [:id, :_destroy, :number],
        addresses_attributes: [:id, :_destroy, :location_type_id, :street, :city, :state, :zip]])
    end
end

app/helpers/people_helper.rb
module PeopleHelper
  def format_address(a)
    [a.street, a.city, a.state, a.zip].compact.join(", ")
  end

  def format_address_table_label(address)
    label = "Address"
    if address.location_type
      label << " (#{address.location_type.name})"
    end
    label
  end

  def phone_list(p)
    p.phones.map(&:number).join(", ")
  end
end

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <%= field_set_tag 'Phones' do %>
    <%= f.fields_for :phones do |phone| %>
      <div class="field">
        <%= phone.label :number %><br>
        <%= phone.text_field :number %>
      </div>
      <% if phone.object.persisted? %>
        <div class="field">
          Delete: <%= phone.check_box :_destroy %>
        </div>
      <% end %>
      <hr>
    <% end %>
  <% end %>

  <%= field_set_tag 'Addresses' do %>
    <%= f.fields_for :addresses do |address| %>
      <div class="field">
        <%= address.label :street %><br>
        <%= address.text_field :street %>
      </div>
      <div class="field">
        <%= address.label :city %><br>
        <%= address.text_field :city %>
      </div>
      <div class="field">
        <%= address.label :state%><br>
        <%= address.text_field :state%>
      </div>
      <div class="field">
        <%= address.label :zip %><br>
        <%= address.text_field :zip %>
      </div>
      <div class="field">
        <%= address.label :location_type %><br>
        <%= address.collection_select :location_type_id, LocationType.all, :id, :name, include_blank: true %>
      </div>
      <% if address.object.persisted? %>
        <div class="field">
          Delete: <%= address.check_box :_destroy %>
        </div>
      <% end %>
      <hr>
    <% end %>
  <% end %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<section class="container">
<h1>Editing person</h1>

<%= render 'form' %>

</section>

<% render "layouts/standard_navbar" %>

app/views/people/index.html.erb
<section class="container-fluid">
<h2>Listing people</h2>
<section class="table-responsive">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone(s)</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= phone_list(person) %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</section>

<%= link_to 'New Person', new_person_path %>
</section>

<% render "layouts/standard_navbar" %>

app/views/people/new.html.erb
<section class="container">
<h1>New person</h1>

<%= render 'form' %>

</section>

<% render "layouts/standard_navbar" %>

app/views/people/show.html.erb
<section class="container">
<h2><%= @person.name %></h2>

<p id="notice"><%= notice %></p>

<table class="table table-striped">
  <tbody>
    <% @person.phones.each do |phone| %>
      <tr>
        <td>Number</td>
        <td><%= phone.number %></td>
      </tr>
    <% end %>
    <% @person.addresses.each do |address| %>
      <tr>
        <td><%= format_address_table_label(address) %></td>
        <td><%= format_address(address) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_person_path(@person) %>
</section>

<% render "layouts/standard_navbar" %>