config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :location_types

  resources :addresses

  resources :phones

  resources :people

end

app/controllers/location_types_controller.rb
class LocationTypesController < ApplicationController
  before_action :set_location_type, only: [:show, :edit, :update, :destroy]

  # GET /location_types
  # GET /location_types.json
  def index
    @location_types = LocationType.all
  end

  # GET /location_types/1
  # GET /location_types/1.json
  def show
  end

  # GET /location_types/new
  def new
    @location_type = LocationType.new
  end

  # GET /location_types/1/edit
  def edit
  end

  # POST /location_types
  # POST /location_types.json
  def create
    @location_type = LocationType.new(location_type_params)

    respond_to do |format|
      if @location_type.save
        format.html { redirect_to @location_type, notice: 'Location type was successfully created.' }
        format.json { render :show, status: :created, location: @location_type }
      else
        format.html { render :new }
        format.json { render json: @location_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /location_types/1
  # PATCH/PUT /location_types/1.json
  def update
    respond_to do |format|
      if @location_type.update(location_type_params)
        format.html { redirect_to @location_type, notice: 'Location type was successfully updated.' }
        format.json { render :show, status: :ok, location: @location_type }
      else
        format.html { render :edit }
        format.json { render json: @location_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /location_types/1
  # DELETE /location_types/1.json
  def destroy
    @location_type.destroy
    respond_to do |format|
      format.html { redirect_to location_types_url, notice: 'Location type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location_type
      @location_type = LocationType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_type_params
      params.require(:location_type).permit([:name, :color])
    end
end

app/helpers/location_types_helper.rb
module LocationTypesHelper
end

app/views/location_types/_form.html.erb
<%= form_for(@location_type) do |f| %>
  <% if @location_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location_type.errors.count, "error") %> prohibited this location_type from being saved:</h2>

      <ul>
      <% @location_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/location_types/edit.html.erb
<h1>Editing location_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @location_type %> |
<%= link_to 'Back', location_types_path %>

app/views/location_types/index.html.erb
<section class="container-fluid">
<h2>Listing Location Types</h2>

<section class="table-responsive">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @location_types.each do |location_type| %>
      <tr>
        <td><%= location_type.name %></td>
        <td><%= location_type.color || "n/a" %></td>
        <td><%= link_to 'Show', location_type %></td>
        <td><%= link_to 'Edit', edit_location_type_path(location_type) %></td>
        <td><%= link_to 'Destroy', location_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</section>

<%= link_to 'New Location type', new_location_type_path %>
</section>
<% render "layouts/standard_navbar" %>

app/views/location_types/new.html.erb
<h1>New location_type</h1>

<%= render 'form' %>

<%= link_to 'Back', location_types_path %>

app/views/location_types/show.html.erb
<section class="container-fluid">
<h2>Location Type</h2>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @location_type.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @location_type.color %>
</p>

<%= link_to 'Edit', edit_location_type_path(@location_type) %> |
<%= link_to 'Back', location_types_path %>
</section>
<% render "layouts/standard_navbar" %>